name: domya-fallen-link
version: '${version}'
main: ru.nyansus.mc.fallenlink.DomyaFallenLink
api-version: '1.21'
author: Domya SMP

commands:
  domyasync:
    permission: domyasync.admin
  link: {}

permissions:
  domyasync.admin:
    default: op
