name: domya-fallen-link
version: '${version}'
main: ru.nyansus.mc.fallenlink.DomyaFallenLink
api-version: '1.21'
author: Domya SMP

commands:
  domyasync:
    description: Domya player statistics synchronization
    usage: /domyasync <sync|reload|status>
    permission: domyasync.admin
  link:
    description: Link Minecraft account with Domya website profile
    usage: /link <code>

permissions:
  domyasync.admin:
    description: Allows managing domya-fallen-link
    default: op
